# Generated by Django 6.0 on 2026-01-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pooja_name', models.CharField(max_length=50)),
                ('pooja_details', models.CharField(max_length=50)),
                ('pooja_amount', models.CharField(max_length=50)),
                ('pooja_time', models.CharField(max_length=50)),
            ],
        ),
    ]
