# Generated by Django 6.0 on 2026-01-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_slot',
        ),
    ]
