# Generated by Django 6.0 on 2026-01-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_delete_tbl_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_birthstar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthstar_name', models.CharField(max_length=50)),
            ],
        ),
    ]
