# Generated by Django 6.0 on 2026-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_birthstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_file', models.FileField(upload_to='Assets/Admin/Photos/')),
                ('galery_description', models.CharField(max_length=200)),
            ],
        ),
    ]
