# Generated by Django 6.0 on 2026-01-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_content', models.FileField(upload_to='')),
                ('notification_date', models.CharField(max_length=50)),
            ],
        ),
    ]
