# Generated by Django 6.0 on 2026-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deity_name', models.CharField(max_length=50)),
            ],
        ),
    ]
