# Generated by Django 6.0 on 2026-01-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_deity'),
        ('User', '0004_delete_tbl_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_pooja',
        ),
    ]
