# Generated by Django 6.0 on 2026-01-23 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_delete_tbl_pooja'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pooja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pooja_name', models.CharField(max_length=50)),
                ('pooja_details', models.CharField(max_length=50)),
                ('pooja_amount', models.CharField(max_length=50)),
                ('pooja_time', models.CharField(max_length=50)),
                ('deity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_deity')),
            ],
        ),
    ]
