# Generated by Django 6.0.2 on 2026-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_expence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expence_amount', models.IntegerField()),
                ('expence_date', models.DateField()),
                ('expence_content', models.CharField(max_length=50)),
            ],
        ),
    ]
