# Generated by Django 6.0.2 on 2026-03-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_tbl_expence'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deity',
            name='deity_image',
            field=models.FileField(blank=True, null=True, upload_to='Assets/Admin/Deity/'),
        ),
    ]
