# Generated by Django 6.0.2 on 2026-02-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
        ('User', '0014_remove_tbl_cart_booking_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
