# Generated by Django 6.0.2 on 2026-02-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0017_initial'),
        ('Guest', '0004_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_address', models.TextField()),
                ('user_gender', models.CharField(max_length=10)),
                ('user_dob', models.DateField()),
                ('user_photo', models.FileField(blank=True, null=True, upload_to='Assets/User/Photos/')),
                ('user_password', models.CharField(max_length=255)),
                ('user_is_active', models.BooleanField(default=True)),
                ('user_last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Admin.tbl_place')),
            ],
        ),
    ]
