# Generated by Django 6.0 on 2026-01-23 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_tbl_notification'),
        ('Guest', '0003_initial'),
        ('User', '0002_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=50)),
                ('booking_todate', models.CharField(max_length=50)),
                ('booking_status', models.CharField(max_length=50)),
                ('booking_amount', models.CharField(max_length=50)),
                ('booking_name', models.CharField(max_length=50)),
                ('booking_number', models.CharField(max_length=50)),
                ('birthstar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_birthstar')),
                ('pooja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_pooja')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
