# Generated by Django 6.0 on 2026-01-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_booking',
        ),
    ]
