# Generated by Django 6.0 on 2026-01-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_tbl_booking_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_todate',
            field=models.DateField(),
        ),
    ]
