# Generated by Django 6.0 on 2026-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_tbl_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_status',
            field=models.IntegerField(default=0),
        ),
    ]
