# Generated by Django 6.0 on 2026-01-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_pooja'),
        ('User', '0008_alter_tbl_booking_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_status', models.IntegerField(default=0)),
                ('birthstar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_birthstar')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('pooja_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_pooja')),
            ],
        ),
    ]
