# Generated by Django 6.0 on 2026-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_todate',
            field=models.DateField(null=True),
        ),
    ]
