# Generated by Django 6.0 on 2026-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_tbl_booking_booking_todate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='birthstar_id',
        ),
        migrations.RemoveField(
            model_name='tbl_booking',
            name='booking_name',
        ),
        migrations.AddField(
            model_name='tbl_cart',
            name='cart_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
