# Generated by Django 6.0 on 2026-02-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_remove_tbl_booking_birthstar_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='pooja_id',
        ),
    ]
