# Generated by Django 6.0 on 2026-02-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_tbl_pooja'),
        ('User', '0012_remove_tbl_booking_pooja_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cart',
            name='birthstar_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_birthstar'),
        ),
    ]
