# Generated by Django 6.0.2 on 2026-02-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_tbl_cart_birthstar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='birthstar_id',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='pooja_id',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
