# Generated by Django 6.0.2 on 2026-02-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0017_initial'),
        ('Guest', '0005_initial'),
        ('User', '0014_remove_tbl_cart_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=30, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_from_date', models.DateField()),
                ('booking_to_date', models.DateField(blank=True, null=True)),
                ('booking_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled'), (3, 'Completed')], default=0)),
                ('booking_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_booking_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('devotee_name', models.CharField(blank=True, max_length=80, null=True)),
                ('gotra', models.CharField(blank=True, max_length=60, null=True)),
                ('special_request', models.CharField(blank=True, max_length=255, null=True)),
                ('pooja_date', models.DateField()),
                ('pooja_time', models.TimeField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled'), (3, 'Completed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birthstar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Admin.tbl_birthstar')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='User.tbl_booking')),
                ('pooja_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Admin.tbl_pooja')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(default='online', max_length=30)),
                ('payment_provider', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_txn_id', models.CharField(blank=True, max_length=120, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.IntegerField(choices=[(0, 'Initiated'), (1, 'Success'), (2, 'Failed'), (3, 'Refunded')], default=0)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='User.tbl_booking')),
            ],
        ),
        migrations.AddIndex(
            model_name='tbl_booking',
            index=models.Index(fields=['booking_number'], name='User_tbl_bo_booking_8807f9_idx'),
        ),
        migrations.AddIndex(
            model_name='tbl_booking',
            index=models.Index(fields=['booking_status'], name='User_tbl_bo_booking_8510e2_idx'),
        ),
        migrations.AddIndex(
            model_name='tbl_booking',
            index=models.Index(fields=['booking_from_date'], name='User_tbl_bo_booking_dbba6b_idx'),
        ),
        migrations.AddIndex(
            model_name='tbl_booking_item',
            index=models.Index(fields=['pooja_date'], name='User_tbl_bo_pooja_d_53c7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='tbl_booking_item',
            index=models.Index(fields=['item_status'], name='User_tbl_bo_item_st_815622_idx'),
        ),
    ]
