# Generated by Django 6.0.2 on 2026-03-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='feedback_content',
            field=models.CharField(max_length=500),
        ),
    ]
