# Generated by Django 6.0.2 on 2026-03-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_tbl_feedback_feedback_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_feedback',
            name='feedback_content',
            field=models.CharField(max_length=1000),
        ),
    ]
